const grid=document.getElementById("recipeGrid"),dialog=document.getElementById("recipeDialog"),details=document.getElementById("recipeDetails");
const recipes=(window.LIBRARY_CONTENT||[]).filter(entry=>entry.book==="cooking");
const escapeHTML=value=>String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
function card(recipe,index){const image=recipe.image?`<img src="${escapeHTML(recipe.image)}" alt="${escapeHTML(recipe.imageAlt||recipe.title)}">`:`<span class="photo-glyph" aria-hidden="true">☕︎</span>`;return `<button class="recipe-card" data-id="${escapeHTML(recipe.slug)}"><span class="card-number">${String(index+1).padStart(2,"0")}</span><div class="photo">${image}</div><span class="category">${escapeHTML(recipe.type||"Kitchen note")}</span><strong>${escapeHTML(recipe.title)}</strong><span class="open-label">Open recipe →</span></button>`}
function openRecipe(recipe){details.innerHTML=`${recipe.image?`<div class="dialog-photo"><img src="${escapeHTML(recipe.image)}" alt="${escapeHTML(recipe.imageAlt||recipe.title)}"></div>`:""}<p class="kicker">${escapeHTML(recipe.type||"Kitchen note")}</p><h2>${escapeHTML(recipe.title)}</h2><div class="cooking-progress"><span>Recipe progress</span><div><i></i></div></div><article class="recipe-body">${recipe.html}</article>`;dialog.showModal();document.body.classList.add("dialog-open");const steps=[...details.querySelectorAll("li")];steps.forEach(step=>{step.tabIndex=0;step.addEventListener("click",()=>{step.classList.toggle("done");updateProgress()});step.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();step.click()}})});function updateProgress(){const done=steps.filter(step=>step.classList.contains("done")).length;const bar=details.querySelector(".cooking-progress i");if(bar)bar.style.width=`${steps.length?done/steps.length*100:0}%`}}
grid.innerHTML=recipes.length?recipes.map(card).join(""):`<p class="empty">The first recipe is still being written.</p>`;
grid.addEventListener("click",event=>{const button=event.target.closest(".recipe-card");if(button)openRecipe(recipes.find(recipe=>recipe.slug===button.dataset.id))});
document.getElementById("closeRecipe").addEventListener("click",()=>dialog.close());dialog.addEventListener("click",event=>{if(event.target===dialog)dialog.close()});dialog.addEventListener("close",()=>document.body.classList.remove("dialog-open"));

if(!matchMedia("(prefers-reduced-motion: reduce)").matches&&matchMedia("(pointer:fine)").matches){let lastSpark=0;addEventListener("pointermove",event=>{const now=performance.now();if(now-lastSpark<34)return;lastSpark=now;const spark=document.createElement("i");spark.className="ink-spark";spark.style.left=`${event.clientX-5}px`;spark.style.top=`${event.clientY+8}px`;spark.style.setProperty("--spark-size",`${2+Math.random()*2}px`);spark.style.setProperty("--spark-drift",`${-5+Math.random()*10}px`);document.body.appendChild(spark);spark.addEventListener("animationend",()=>spark.remove())},{passive:true})}
