const grid=document.getElementById("recipeGrid"),dialog=document.getElementById("recipeDialog"),details=document.getElementById("recipeDetails");
const recipes=window.RECIPES||[];
const escapeHTML=value=>String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
function card(recipe,index){return `<button class="recipe-card" data-id="${escapeHTML(recipe.id)}"><span class="card-number">${String(index+1).padStart(2,"0")}</span><div class="photo"><img src="${escapeHTML(recipe.image)}" alt="${escapeHTML(recipe.imageAlt)}"></div><span class="category">${escapeHTML(recipe.category)}</span><strong>${escapeHTML(recipe.title)}</strong><span class="open-label">Open recipe →</span></button>`}
function list(items){return `<ol>${items.map(item=>`<li>${escapeHTML(item)}</li>`).join("")}</ol>`}
function openRecipe(recipe){details.innerHTML=`<div class="dialog-photo"><img src="${escapeHTML(recipe.image)}" alt="${escapeHTML(recipe.imageAlt)}"></div><p class="kicker">${escapeHTML(recipe.category)}</p><h2>${escapeHTML(recipe.title)}</h2><blockquote>${escapeHTML(recipe.story)}</blockquote><div class="recipe-columns"><section><h3>Ingredients</h3>${list(recipe.ingredients)}</section><section><h3>Method</h3>${list(recipe.instructions)}</section></div><section class="serving"><h3>Serving note</h3><p>${escapeHTML(recipe.serving)}</p></section><p class="draft-note">${escapeHTML(recipe.note||"")}</p>`;dialog.showModal();document.body.classList.add("dialog-open")}
grid.innerHTML=recipes.length?recipes.map(card).join(""):`<p class="empty">The first recipe is still being written.</p>`;
grid.addEventListener("click",event=>{const button=event.target.closest(".recipe-card");if(button)openRecipe(recipes.find(recipe=>recipe.id===button.dataset.id))});
document.getElementById("closeRecipe").addEventListener("click",()=>dialog.close());dialog.addEventListener("click",event=>{if(event.target===dialog)dialog.close()});dialog.addEventListener("close",()=>document.body.classList.remove("dialog-open"));
